### ISSUE TITLE
Limit the total number of emojis that can be used for categorisation

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#10]
We don't need the smileys and many more emojis for categorisation - also, eagerly loading all emojis in the stream-category selection dialog takes a long time with so many emojis. 

Find the most relevant emojis (see #7) and pick the top-20 or so.

**Comment by bruunand** [comment]
🍔🎉⚽🌇🐕♠🎮🎭🎨

**Comment by theisjendal** [comment]
🍻🏋️‍♂️🚴‍♀️🎫🏟

**Comment by bruunand** [comment]
🎭🎨

**Comment by Minibrams** [comment]
🎅🏻 🏀 🏈 ⚾️🎾🎤🎸 🎻🎮

**Comment by RogviEliasen** [comment]
🎥🏳️‍🌈🎓🎼🎢⛱️🐰

**Comment by mjarlund** [comment]
:soccer: :football: :fire_engine: :police_car: :fireworks: :dancer: :eggplant:

**Comment by OfficialHisha** [comment]
❤️🔥🐈🔫⚱️🔭🛠️🎲🧪

**Comment by RogviEliasen** [comment]
💣

**Comment by BullDuckling** [comment]
🏆☃️🏞️🌲🖥️🏁

**Comment by Minibrams** [comment]
thank u vvvvv much
