### ISSUE TITLE
Stream crashes to MainActivity if started twice

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#11]
When starting a stream two times after going through the stream categorising dialog, the stream crashes to the main screen. 

Steps to recreate: 
1. Press the "Stream" option button in the MainActivity
2. From the stream categorising dialog, press "Go"
3. Press the "Back" Android control
4. Press "Go" again

(on the begin-stream-dialog branch)

**Comment by bruunand** [comment]
Heyhey hvorfor skal jeg assignes her

**Comment by Minibrams** [comment]
Tænkte at det var dig der havde implementeret stream, så det var nok nemmest wreh

**Comment by bruunand** [comment]
Fair nok :smiley_cat: Jeg kigger på det :+1:
