### ISSUE TITLE
Add the option so users can type the name of an emoji and select it from there instead of selecting from the emoji list view

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#12]
It can be hard to find the proper emojis from a large list of emojis. 
The standard Google Keyboard can recommend emojis from the words you type. 
Add this as a secondary option for users when categorising a stream. 

Make sure that emojis that are added in this way are combined with the emojis extracted from the list view when starting the stream.

**Comment by bruunand** [comment]
Is it really necessary if we limit the number of selectable emojis to e.g. 9?

**Comment by Minibrams** [comment]
In that case no, but will it be that few?

**Comment by bruunand** [comment]
Only time will tell.

**Comment by Minibrams** [comment]
Did the thing
