### ISSUE TITLE
Extract the actual geo-location of the broadcaster when starting a broadcast

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#20]
In the InitializeBroadcastActivity, fetch the actual geo-location (lat, lon) of the client and create a broadcaster DB object with that info instead of the placeholder info that is used right now.

On branch begin-stream-dialog.

**Comment by bruunand** [comment]
Need to add permission request for fine location when starting stream (the same place where we ask for camera and audio).
