### ISSUE TITLE
Calculate the optimal output resolution when starting a broadcast

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#21]
In the BroadcastActivity, we are currently setting the output resolution to the same as the preview resolution, that is, the same that the broadcaster is seeing on their screen. This is not necessarily the optimal resolution.

**Comment by bruunand** [comment]
Higher res = more battery consumption, so we should prefer a middle grund like 1280x720. At least it should be in a 16:9 aspect ratio.
