### ISSUE TITLE
Map Emojis disappear when changing between landscape/vertical

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#46]
Probably because the view changes but the data is not immediately fetched. Make sure that emojis are displayed immediately when the user changes between vertical/horizontal.

**Comment by BullDuckling** [comment]
Now updates map on main activity onCreate.
commit 973708837093fa380e7305e8e1039c5262a3608f

**Comment by BullDuckling** [comment]
#

**Comment by BullDuckling** [comment]
#
