### ISSUE TITLE
App crash caused by delayed failure measure

### ISSUE THREAD

**Issue by bruunand** [sea-shanty-2/envue#55]
If the app fails to retrieve profile information, onProfileFetchFailure is called. However, if the user has pressed back before that method is called, the app fails to bind the message box to the old activity view since it has changed, causing the app to crash.

**Comment by BullDuckling** [comment]
Added check if activity is destroyed. Unsure if this fixed it.
aa49396c872c999d91d73124fe044f2fbafe73ab
