### ISSUE TITLE
Sort emojis by categorising-potential

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#7]
In the "begin-stream"-dialog, the first emojis shown are the standard smileys. 
Instead, we should rank all emoji's w.r.t. their expected number of uses in categorising so that these are shown first (e.g. a city, music, party, science, etc). 

Use the "begin-stream-dialog" branch.

**Comment by bruunand** [comment]
Is this order w.r.t. existing nearby streams or a fixed order we determine? (Could be both)

**Comment by Minibrams** [comment]
Let's start with fixed as a baseline for when no other streamers are around. Making it dynamic w.r.t. nearby trending categories could be an extension to this.
