### ISSUE TITLE
Save the selected emojis as a one-hot vector in the begin-stream dialog.

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#9]
Implement a method (optimally in the BroadcastCategoryListAdapter class, otherwise in the InitializeBroadcastActivity class) that outputs the selected emojis as a one-hot vector. This is to be used in the future as the vector-description of a stream to be used by the clustering API.

**Comment by bruunand** [comment]
Emoji2vec

**Comment by Minibrams** [comment]
Hvis du nu deltog i standup meetings kunne du være med til at tage de beslutninger :) :) :) :) :)

**Comment by bruunand** [comment]
Nu skal du høre her, din lille rotte (og hør godt efter). Jeg vil meget hellere deltage i dit lorte standup meeting end at ligge herhjemme og være syg. Bare fordi jeg ikke er der betyder det ikke at der kan tages FUCKING DUMME BESLUTNINGER. KAN DU FATTE DET? HVA?

**Comment by Minibrams** [comment]
Emoji2Vec er: 
1. Stort og tungt
2. Meget teori
3. Noget ingen har undersøgt endnu
4. FUCKING overengineering

OneHot er: 
1. Simpelt i teori
2. Hurtigt at implementere så vi kan se om stream-creation virker sammen med clustering

Godt så :)

**Comment by bruunand** [comment]
OneHot er helt fint hvis vi begrænser hvilke emojis vi kan bruge :-)

**Comment by bruunand** [comment]
Ellers er et klart problem hvordan onehot giver mening til f.eks. en koncert, hvor valget af emojis kunne være en af 🎵🎸🎶🎼🎹🎺🎷🤘. Det ville nok være fint kun at tillade 🎵 her, så vi har en større chance for at flere broadcasters vælger den.

**Comment by Minibrams** [comment]
Implemented in 745ad66c72c9ccb264b39a44cdbf603f4bcd88b3
